version: "3"

services:
  web:
    image: python_app
    environment:
      PORT: 80
      DB_HOST: "db"
    ports:
      - "8080:80"
    mem_limit: 1g
    cpus: 1

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
    mem_limit: 1g
    cpus: 1

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: "db"
    ports:
      - "8081:80"
    mem_limit: 1g
    cpus: 1