# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "super_box"

  config.vm.define "alice" do |alice|
    alice.vm.hostname = "alice.tp3.b2"
    alice.vm.network "private_network", ip: "10.3.1.11"
    alice.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
  end

  config.vm.define "bob" do |bob|
    bob.vm.hostname = "bob.tp3.b2"
    bob.vm.network "private_network", ip: "10.3.1.200"
    bob.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
    end
  end

  config.vm.define "eve" do |eve|
    eve.vm.hostname = "eve.tp3.b2"
    eve.vm.network "private_network", ip: "10.3.1.57"
    eve.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
  end
end